<template><view class="sub-page"><view class="nav"><text @tap="back">‹</text><b>{{ article.title || '内容详情' }}</b><text v-if="article.id && type === 'script'" class="share" @tap="share">分享</text><view v-else /></view><view v-if="article.id" class="body"><view class="cover">{{ type === 'script' ? '推广话术' : '平台公告' }}</view><text class="title">{{ article.title }}</text><view class="meta"><text>{{ article.date }}</text><text>{{ article.author || '平台运营' }}</text></view><view class="line"/><text class="content">{{ article.content || article.summary || '暂无正文内容' }}</text></view><view v-else-if="!loading" class="empty">内容不存在或已失效</view><view v-else class="empty">内容加载中…</view></view></template>
<script setup>
import { onMounted, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { enforcePortal } from '../../core/route-guard'
import { getAnnouncement, getPromotionMaterial, reportPromotionMaterialEvent, unwrap } from '../../services/agent'
const type=ref('notice'),id=ref(''),article=ref({}),loading=ref(false)
onLoad((options)=>{type.value=options?.type||'notice';id.value=String(options?.id||'')})
onMounted(()=>{if(enforcePortal('agent')&&id.value)loadArticle()})
function normalizeArticle(data){return{id:data.material_no||data.materialNo||data.announcement_no||data.announcementNo||data.id||id.value,title:data.title||'',summary:data.summary||'',content:data.content||data.body||data.text||'',date:String(data.published_at||data.publishedAt||data.created_at||data.createdAt||'').slice(0,10),author:data.author||data.publisher||data.operator_name||''}}
async function loadArticle(){loading.value=true;try{const response=type.value==='script'?await getPromotionMaterial(id.value):await getAnnouncement(id.value);article.value=normalizeArticle(unwrap(response)||{})}catch(error){article.value={};uni.showToast({title:error.message||'内容加载失败',icon:'none'})}finally{loading.value=false}}
function back(){uni.navigateBack()}
function share(){const content=article.value.content||article.value.summary||article.value.title;if(!content)return;uni.setClipboardData({data:content,success:async()=>{uni.showToast({title:'话术已复制',icon:'success'});try{await reportPromotionMaterialEvent(article.value.id,{action:'copy',channel:'detail'},`promotion-${Date.now()}-${Math.random().toString(36).slice(2,10)}`)}catch(error){console.warn('Failed to report promotion copy event',error)}}})}
</script>
<style lang="scss" scoped>.sub-page{min-height:100vh;background:#fff;color:#27314a}.nav{display:flex;justify-content:space-between;align-items:center;height:calc(102rpx + env(safe-area-inset-top));padding:env(safe-area-inset-top) 32rpx 0;border-bottom:1rpx solid #edf0f4;box-sizing:border-box;font-size:29rpx}.nav>text,.nav>view{width:76rpx;color:#5865f2;font-size:60rpx;line-height:1}.nav .share{font-size:25rpx;text-align:right}.nav b{flex:1;overflow:hidden;text-align:center;text-overflow:ellipsis;white-space:nowrap}.body{padding:34rpx}.cover{display:flex;align-items:center;justify-content:center;height:300rpx;border-radius:24rpx;background:linear-gradient(135deg,#e8ebff,#cdd3ff);color:#5966f3;font-size:42rpx;font-weight:750;letter-spacing:3rpx}.title{display:block;margin-top:36rpx;font-size:42rpx;font-weight:760;line-height:1.35}.meta{display:flex;justify-content:space-between;margin-top:21rpx;color:#99a2b2;font-size:21rpx}.line{height:1rpx;margin:28rpx 0;background:#edf0f4}.content{display:block;white-space:pre-wrap;color:#526078;font-size:27rpx;line-height:1.9}.empty{padding-top:300rpx;color:#8790a1;text-align:center;font-size:28rpx}</style>
